# Generated by Django 3.1.7 on 2021-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneandadress',
            name='namber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phoneandadress',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
