# Generated by Django 3.1.7 on 2021-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210331_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=250)),
                ('state', models.CharField(default='prossesing', max_length=250)),
                ('type', models.IntegerField(choices=[(1, 'Is Target'), (2, 'Is Writher')])),
                ('star', models.IntegerField(choices=[(1, 'O Stea'), (2, 'Doua Stele'), (3, 'Trei Stele')], default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='phoneandaddress',
            old_name='namber',
            new_name='number',
        ),
    ]
