# Generated by Django 3.1.7 on 2021-04-24 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210407_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='star',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars')], default=3),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='type',
            field=models.IntegerField(choices=[(1, 'Is Target'), (2, 'Is Writer')]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
