# Generated by Django 3.1.7 on 2021-03-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producers', '0004_auto_20210329_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='producer_profile',
        ),
        migrations.AddField(
            model_name='producer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='producer', serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
