# Generated by Django 3.1.7 on 2021-04-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producers', '0008_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Producers',
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(default=None, upload_to='pictures')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producers.products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
