# Generated by Django 3.1.7 on 2021-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0009_auto_20210406_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
