# Generated by Django 3.1.7 on 2021-05-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0011_auto_20210412_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id_owner',
            new_name='owner',
        ),
    ]
