# Generated by Django 3.1.7 on 2021-04-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_data', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField()),
                ('status', models.TextField(choices=[('the order was placed', 'Created'), ('processing order', 'Processing'), ('the order is ready', 'Ready For Pickup'), ('client received the order', 'Completed')], default='the order was placed')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
                ('id_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
